"""Default runtime policy values."""
from __future__ import annotations

LANGUAGE_DEFAULTS = {
    "python": {"enabled": False},
    "typescript": {"enabled": False},
    "java": {"enabled": False},
}
DEFAULT_TEMPERATURE = 0.0
DEFAULT_LOG_LEVEL = "INFO"
DEFAULT_LOG_DEBUG = False
DEFAULT_LOG_STRUCTURED = False
DEFAULT_LOG_MODULE_LEVELS: dict[str, str] = {}
DEFAULT_DB_TIMEOUT = 120.0
DEFAULT_GIT_TIMEOUT = 30.0
DEFAULT_LLM_TIMEOUT = 30.0
DEFAULT_LLM_MAX_RETRIES = 3

DEFAULT_LLM_PROVIDER = "openai"
DEFAULT_LLM_MODEL = "gpt-4.1"

__all__ = [
    "LANGUAGE_DEFAULTS",
    "DEFAULT_TEMPERATURE",
    "DEFAULT_LOG_LEVEL",
    "DEFAULT_LOG_DEBUG",
    "DEFAULT_LOG_STRUCTURED",
    "DEFAULT_LOG_MODULE_LEVELS",
    "DEFAULT_DB_TIMEOUT",
    "DEFAULT_GIT_TIMEOUT",
    "DEFAULT_LLM_TIMEOUT",
    "DEFAULT_LLM_MAX_RETRIES",
    "DEFAULT_LLM_PROVIDER",
    "DEFAULT_LLM_MODEL",
]
