# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Dmitry Chigrin & MegaScienta

"""Shared ingestion data structures.

Structural analysis results may also carry transient observed callsite data
produced during extraction. These observations are not accepted or finalized
calls; artifact processing owns any later filtering and promotion.
"""

from __future__ import annotations

from dataclasses import InitVar, dataclass, field
from pathlib import Path
from typing import TYPE_CHECKING, Dict, List, Optional

from .path_validation import validate_record_path_containment

if TYPE_CHECKING:
    from ..languages.common.ir import LocalBindingFact


@dataclass
class FileRecord:
    path: Path
    relative_path: Path
    language: str


@dataclass
class FileMetadata:
    record: FileRecord
    file_id: str = ""
    blob_sha: str = ""
    size: int = 0
    line_count: int = 0


@dataclass
class FileSnapshot(FileMetadata):
    content: InitVar[Optional[bytes]] = None
    _content: Optional[bytes] = field(default=None, repr=False)

    def __post_init__(self, content: Optional[bytes]) -> None:
        if content is not None:
            self._content = content

    @property
    def content(self) -> bytes:
        if self._content is None:
            validate_record_path_containment(
                self.record.path, self.record.relative_path
            )
            self._content = self.record.path.read_bytes()
        return self._content

    @content.setter
    def content(self, value: Optional[bytes]) -> None:
        self._content = value


@dataclass
class SemanticNodeRecord:
    language: str
    node_type: str
    qualified_name: str
    display_name: str
    file_path: Path
    start_line: int
    end_line: int
    start_byte: Optional[int] = None
    end_byte: Optional[int] = None
    file_id: Optional[str] = None
    metadata: Optional[Dict[str, object]] = None

    def __post_init__(self) -> None:
        if not self.language:
            raise ValueError("language cannot be empty")
        if not self.node_type:
            raise ValueError("node_type cannot be empty")
        if not self.qualified_name:
            raise ValueError("qualified_name cannot be empty")
        if not self.display_name:
            raise ValueError("display_name cannot be empty")
        if self.start_line < 1:
            raise ValueError(f"start_line must be >= 1, got {self.start_line}")
        if self.end_line < self.start_line:
            raise ValueError(
                f"end_line ({self.end_line}) must be >= start_line ({self.start_line})"
            )
        if self.start_byte is not None and self.start_byte < 0:
            raise ValueError(f"start_byte must be >= 0, got {self.start_byte}")
        if self.start_byte is not None and self.end_byte is not None:
            if self.end_byte < self.start_byte:
                raise ValueError(
                    f"end_byte ({self.end_byte}) must be >= start_byte ({self.start_byte})"
                )


@dataclass
class CallRecord:
    """Observed callsite metadata generated by language analyzers.

    `callee_identifiers` stores extracted candidate identifier text for a
    syntactic callsite observation. It is intentionally pre-finalization and may
    include unresolved, ambiguous, external, or later-filtered identifiers.
    """

    qualified_name: str
    node_type: str
    callee_identifiers: List[str]
    local_binding_facts: List["LocalBindingFact"] = field(default_factory=list)


@dataclass
class EdgeRecord:
    src_language: str
    src_node_type: str
    src_qualified_name: str
    dst_language: str
    dst_node_type: str
    dst_qualified_name: str
    edge_type: str
    confidence: float = 1.0


@dataclass
class AnalysisResult:
    """Per-file structural analysis output plus transient callsite observations."""

    nodes: List[SemanticNodeRecord] = field(default_factory=list)
    edges: List[EdgeRecord] = field(default_factory=list)
    call_records: List[CallRecord] = field(default_factory=list)
    diagnostics: Dict[str, object] = field(default_factory=dict)
